import type { UnitType } from './types.ts';
import { NO_FIRE, resolve } from './unit-type-resolve.ts';

/** Special role units (5) */

export const carrier: UnitType = resolve({
  name: 'Carrier',
  cost: 9,
  size: 22,
  hp: 140,
  speed: 75,
  turnRate: 1,
  fireRate: 1.2,
  range: 250,
  damage: 2,
  shape: 7,
  trailInterval: 1,
  mass: 15,
  accel: 2.5,
  drag: 0.9,
  leadAccuracy: 0.5,
  role: 'special',
  spawns: true,
  engageMin: 150,
  engageMax: 230,
  retreatHpRatio: 0.3,
  clusterSize: 1,
  description: 'ドローンを定期射出する母艦。自身も砲撃で援護する。',
  attackDesc: 'ドローン射出＋砲撃援護',
});

export const teleporter: UnitType = resolve({
  name: 'Teleporter',
  cost: 4,
  size: 8,
  hp: 12,
  speed: 150,
  turnRate: 4,
  fireRate: 0.6,
  range: 160,
  damage: 4,
  shape: 13,
  trailInterval: 0.4,
  mass: 2,
  accel: 8.0,
  drag: 2.5,
  leadAccuracy: 0.3,
  role: 'special',
  teleports: true,
  engageMin: 30,
  engageMax: 120,
  clusterSize: 3,
  description: '空間を3連跳躍し、着地衝撃で敵陣形を崩しつつ精密射撃を放つ次元奇襲機。',
  attackDesc: '3連ブリンク→着地衝撃＋精密射撃（計6発）',
});

export const disruptor: UnitType = resolve({
  name: 'Disruptor',
  cost: 4,
  size: 9,
  hp: 14,
  speed: 110,
  turnRate: 3,
  fireRate: 4.5,
  range: 200,
  damage: 2,
  shape: 11,
  trailInterval: 0.5,
  mass: 3,
  accel: 7.0,
  drag: 2.0,
  leadAccuracy: 0,
  role: 'special',
  emp: true,
  engageMin: 80,
  engageMax: 170,
  boost: { multiplier: 1.8, duration: 0.3, cooldown: 3.5, triggerRange: 200 },
  retreatHpRatio: 0.35,
  clusterSize: 3,
  description: '電磁パルスを放射し、範囲内の全敵を行動不能にする電子戦機。',
  attackDesc: 'EMPバースト（1.5秒スタン）',
});

export const scrambler: UnitType = resolve({
  name: 'Scrambler',
  cost: 4,
  size: 11,
  hp: 18,
  speed: 105,
  turnRate: 2.8,
  fireRate: NO_FIRE,
  range: 0,
  damage: 0,
  shape: 17,
  trailInterval: 0.5,
  mass: 3,
  accel: 5.5,
  drag: 1.8,
  leadAccuracy: 0,
  role: 'special',
  scrambles: true,
  supportFollow: 1,
  engageMin: 0,
  engageMax: 0,
  boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 130 },
  retreatHpRatio: 0.4,
  clusterSize: 3,
  description: '電磁妨害波で敵の射撃性能を劣化させる電子戦支援艦。範囲内の敵は射程・精度・発射速度が低下する。',
  attackDesc: '電磁妨害フィールド（敵デバフ）',
});

export const mothership: UnitType = resolve({
  name: 'Mothership',
  cost: 0,
  size: 45,
  hp: 500,
  speed: 35,
  turnRate: 0.3,
  fireRate: NO_FIRE,
  range: 0,
  damage: 0,
  shape: 19,
  trailInterval: 1.5,
  mass: 50,
  accel: 1.5,
  drag: 0.5,
  leadAccuracy: 0,
  role: 'special',
  clusterSize: 0, // 生産対象外
  engageMin: 300, // 操舵用: 武装なしだが敵との距離 300-1000 を保つ回避行動に使用
  engageMax: 1000,
  description: '艦隊の中核たる母艦。この艦が撃沈されると敗北となる。',
  attackDesc: 'なし',
});
