import type { UnitType } from './types.ts';

export const TYPES: UnitType[] = [
  {
    name: 'Drone',
    size: 4,
    hp: 3,
    speed: 220,
    turnRate: 5.5,
    fireRate: 0.25,
    range: 110,
    damage: 1,
    shape: 0,
    trailInterval: 0.3,
    mass: 1,
    accel: 10.0,
    drag: 2.5,
    swarm: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 2.5, triggerRange: 120 },
    description: '群行動する小型機。仲間が多いほど攻撃力が上がる。',
    attackDesc: 'スウォームパルス（同型近傍数で威力増加）',
  },
  {
    name: 'Fighter',
    size: 7,
    hp: 10,
    speed: 180,
    turnRate: 4.5,
    fireRate: 0.9,
    range: 170,
    damage: 2,
    shape: 1,
    trailInterval: 0.5,
    mass: 2,
    accel: 8.0,
    drag: 2.0,
    burst: 3,
    boost: { multiplier: 2.0, duration: 0.4, cooldown: 3.0, triggerRange: 180 },
    description: '3連バーストで敵を圧倒する主力戦闘機。',
    attackDesc: '3連バースト射撃',
  },
  {
    name: 'Bomber',
    size: 10,
    hp: 20,
    speed: 120,
    turnRate: 2.5,
    fireRate: 2.8,
    range: 220,
    damage: 5,
    shape: 2,
    trailInterval: 0.7,
    mass: 4,
    accel: 5.0,
    drag: 1.5,
    aoe: 42,
    carpet: 4,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
    description: '範囲爆発する大型爆弾を投下。',
    attackDesc: 'AOE爆弾（範囲ダメージ）',
  },
  {
    name: 'Cruiser',
    size: 15,
    hp: 50,
    speed: 75,
    turnRate: 1.5,
    fireRate: 1.5,
    range: 350,
    damage: 8,
    shape: 16,
    trailInterval: 0.9,
    mass: 10,
    accel: 3.5,
    drag: 1.2,
    sweep: true,
    boost: { multiplier: 1.4, duration: 0.3, cooldown: 5.0, triggerRange: 250 },
    description: '掃射ビームで広範囲を薙ぎ払う重巡洋艦。',
    attackDesc: '掃射ビーム（CD発動→±30°一掃）',
  },
  {
    name: 'Flagship',
    size: 30,
    hp: 200,
    speed: 35,
    turnRate: 0.5,
    fireRate: 1.8,
    range: 400,
    damage: 8,
    shape: 24,
    trailInterval: 1.3,
    mass: 30,
    accel: 2.0,
    drag: 0.8,
    broadside: true,
    description: '重砲斉射で中型艦を圧倒する艦隊の中核。スウォームには弱い。',
    attackDesc: 'チャージ→3連重砲＋側面砲（対中型特化）',
  },
  {
    name: 'Healer',
    size: 11,
    hp: 12,
    speed: 130,
    turnRate: 3.5,
    fireRate: 2,
    range: 160,
    damage: 1,
    shape: 25,
    trailInterval: 0.4,
    mass: 2,
    accel: 7.0,
    drag: 2.0,
    heals: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.0, triggerRange: 160 },
    description: '回復ビームで味方を修復。',
    attackDesc: '回復ビーム（味方HP回復）',
  },
  {
    name: 'Reflector',
    size: 13,
    hp: 22,
    speed: 105,
    turnRate: 2.8,
    fireRate: 0.3,
    range: 130,
    damage: 1,
    shape: 26,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    reflects: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
    description: '敵弾を反射して跳ね返す。周囲に被ダメ軽減バリア。',
    attackDesc: '弾丸反射＋弱射撃',
  },
  {
    name: 'Carrier',
    size: 22,
    hp: 90,
    speed: 50,
    turnRate: 1,
    fireRate: 1.2,
    range: 250,
    damage: 2,
    shape: 7,
    trailInterval: 1,
    mass: 15,
    accel: 2.5,
    drag: 0.9,
    spawns: true,
    description: '定期的にドローン4体を生産する母艦。',
    attackDesc: 'ドローン生産＋通常射撃',
  },
  {
    name: 'Sniper',
    size: 9,
    hp: 8,
    speed: 90,
    turnRate: 2,
    fireRate: 2.8,
    range: 600,
    damage: 18,
    shape: 8,
    trailInterval: 0.4,
    mass: 3,
    accel: 4.0,
    drag: 1.5,
    description: '超長射程レールガンで一撃必殺。',
    attackDesc: 'レールガン＋トレーサーライン',
  },
  {
    name: 'Lancer',
    size: 12,
    hp: 65,
    speed: 260,
    turnRate: 2,
    fireRate: 999,
    range: 0,
    damage: 0,
    shape: 9,
    trailInterval: 0.8,
    mass: 12,
    accel: 6.0,
    drag: 0.4,
    rams: true,
    boost: { multiplier: 2.5, duration: 0.5, cooldown: 2.0, triggerRange: 250 },
    description: '高速体当たりで敵を粉砕する。',
    attackDesc: '高速体当たり（ノックバック大）',
  },
  {
    name: 'Launcher',
    size: 11,
    hp: 18,
    speed: 100,
    turnRate: 2,
    fireRate: 2.8,
    range: 420,
    damage: 6,
    shape: 6,
    trailInterval: 0.6,
    mass: 5,
    accel: 5.0,
    drag: 1.5,
    burst: 3,
    homing: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 300 },
    description: 'ホーミングミサイルで追尾攻撃。',
    attackDesc: '追尾ミサイル（煙トレイル）',
  },
  {
    name: 'Disruptor',
    size: 9,
    hp: 14,
    speed: 110,
    turnRate: 3,
    fireRate: 4.5,
    range: 200,
    damage: 2,
    shape: 11,
    trailInterval: 0.5,
    mass: 3,
    accel: 7.0,
    drag: 2.0,
    emp: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 3.5, triggerRange: 200 },
    description: '電磁パルスで範囲スタン。',
    attackDesc: '範囲スタン（1.5秒行動不能）',
  },
  {
    name: 'Beam Frig.',
    size: 13,
    hp: 30,
    speed: 85,
    turnRate: 1.8,
    fireRate: 0.1,
    range: 300,
    damage: 0.8,
    shape: 5,
    trailInterval: 0.6,
    mass: 6,
    accel: 4.0,
    drag: 1.2,
    beam: true,
    boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.5, triggerRange: 250 },
    description: '集中照射で単体を焼く。照射が長いほど威力増大。',
    attackDesc: '集中ビーム（ランプアップダメージ）',
  },
  {
    name: 'Teleporter',
    size: 8,
    hp: 9,
    speed: 150,
    turnRate: 4,
    fireRate: 0.6,
    range: 160,
    damage: 5,
    shape: 13,
    trailInterval: 0.4,
    mass: 2,
    accel: 8.0,
    drag: 2.5,
    teleports: true,
    description: 'ワープし全方位バースト射撃。',
    attackDesc: 'テレポート→全方位バースト',
  },
  {
    name: 'Arcer',
    size: 10,
    hp: 16,
    speed: 115,
    turnRate: 3,
    fireRate: 2,
    range: 250,
    damage: 4,
    shape: 15,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    chain: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.5, triggerRange: 220 },
    description: '電撃が最大5体の敵に連鎖。',
    attackDesc: 'チェーンライトニング（5体連鎖）',
  },
];

/** pools.ts と同パターンの安全アクセサ */
export function getUnitType(id: number): UnitType {
  const t = TYPES[id];
  if (t === undefined) throw new RangeError(`Invalid unit type id: ${id}`);
  return t;
}

/** TYPES配列のnameからインデックスを導出する。存在しない名前はコンパイル時に弾けないためランタイムエラー */
export function unitTypeIndex(name: string): number {
  const idx = TYPES.findIndex((t) => t.name === name);
  if (idx === -1) throw new RangeError(`Unknown unit type name: ${name}`);
  return idx;
}
