import type { UnitType } from './types.ts';

export const TYPES: UnitType[] = [
  {
    name: 'Drone',
    size: 4,
    hp: 3,
    speed: 220,
    turnRate: 5.5,
    fireRate: 0.25,
    range: 110,
    damage: 1,
    shape: 0,
    trailInterval: 0.3,
    mass: 1,
    accel: 10.0,
    drag: 2.5,
    leadAccuracy: 0.3,
    swarm: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 2.5, triggerRange: 120 },
    description: '編隊連携に特化した無人機。同型機が密集するほど火力が増大する。',
    attackDesc: 'スウォームパルス（近傍密度連動）',
  },
  {
    name: 'Fighter',
    size: 7,
    hp: 10,
    speed: 180,
    turnRate: 4.5,
    fireRate: 0.9,
    range: 170,
    damage: 2,
    shape: 1,
    trailInterval: 0.5,
    mass: 2,
    accel: 8.0,
    drag: 2.0,
    leadAccuracy: 0.7,
    burst: 3,
    boost: { multiplier: 2.0, duration: 0.4, cooldown: 3.0, triggerRange: 180 },
    description: '3連バースト射撃を備えた汎用主力機。前線の中核を担う。',
    attackDesc: '3連バースト射撃',
  },
  {
    name: 'Bomber',
    size: 10,
    hp: 20,
    speed: 120,
    turnRate: 2.5,
    fireRate: 2.8,
    range: 220,
    damage: 5,
    shape: 2,
    trailInterval: 0.7,
    mass: 4,
    accel: 5.0,
    drag: 1.5,
    leadAccuracy: 0.4,
    aoe: 42,
    carpet: 4,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
    description: '広域爆圧弾を投下する重爆撃機。密集陣形に絶大な効果を発揮。',
    attackDesc: '絨毯爆撃（範囲爆圧ダメージ）',
  },
  {
    name: 'Cruiser',
    size: 15,
    hp: 50,
    speed: 75,
    turnRate: 1.5,
    fireRate: 1.5,
    range: 350,
    damage: 8,
    shape: 16,
    trailInterval: 0.9,
    mass: 10,
    accel: 3.5,
    drag: 1.2,
    leadAccuracy: 0,
    sweep: true,
    boost: { multiplier: 1.4, duration: 0.3, cooldown: 5.0, triggerRange: 250 },
    description: '広角ビームで戦域を薙ぎ払う重巡洋艦。制圧力に優れる。',
    attackDesc: '掃射ビーム（±30°弧状一掃）',
  },
  {
    name: 'Flagship',
    size: 30,
    hp: 200,
    speed: 35,
    turnRate: 0.5,
    fireRate: 1.8,
    range: 400,
    damage: 8,
    shape: 24,
    trailInterval: 1.3,
    mass: 30,
    accel: 2.0,
    drag: 0.8,
    leadAccuracy: 0.85,
    broadside: true,
    description: '重砲斉射で中型艦を圧倒する艦隊旗艦。対小型群には脆弱。',
    attackDesc: '蓄砲→3連主砲＋舷側砲（対中型特化）',
  },
  {
    name: 'Healer',
    size: 11,
    hp: 12,
    speed: 130,
    turnRate: 3.5,
    fireRate: 2,
    range: 160,
    damage: 1,
    shape: 25,
    trailInterval: 0.4,
    mass: 2,
    accel: 7.0,
    drag: 2.0,
    leadAccuracy: 0.3,
    heals: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.0, triggerRange: 160 },
    description: '修復ビームで味方艦の損傷を回復する支援艦。',
    attackDesc: '修復ビーム（味方HP回復）',
  },
  {
    name: 'Reflector',
    size: 13,
    hp: 22,
    speed: 105,
    turnRate: 2.8,
    fireRate: 0.3,
    range: 130,
    damage: 1,
    shape: 26,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    leadAccuracy: 0.15,
    reflects: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
    description: '敵弾を反射する防壁を展開し、周囲の被弾を軽減する防衛艦。',
    attackDesc: '弾体反射＋減衰シールド',
  },
  {
    name: 'Carrier',
    size: 22,
    hp: 90,
    speed: 50,
    turnRate: 1,
    fireRate: 1.2,
    range: 250,
    damage: 2,
    shape: 7,
    trailInterval: 1,
    mass: 15,
    accel: 2.5,
    drag: 0.9,
    leadAccuracy: 0.5,
    spawns: true,
    description: 'ドローンを定期射出する母艦。自身も砲撃で援護する。',
    attackDesc: 'ドローン射出＋砲撃援護',
  },
  {
    name: 'Sniper',
    size: 9,
    hp: 8,
    speed: 90,
    turnRate: 2,
    fireRate: 2.8,
    range: 600,
    damage: 18,
    shape: 8,
    trailInterval: 0.4,
    mass: 3,
    accel: 4.0,
    drag: 1.5,
    leadAccuracy: 0.95,
    massWeight: 0.15,
    engageMin: 300,
    engageMax: 500,
    cooldownResetOnKill: 0.8,
    description: '超長射程の貫通レールガンで高価値目標を狙撃。撃破ごとに装填が加速。',
    attackDesc: '貫通レールガン（撃破時装填加速）',
  },
  {
    name: 'Lancer',
    size: 12,
    hp: 65,
    speed: 260,
    turnRate: 2,
    fireRate: 999,
    range: 0,
    damage: 0,
    shape: 9,
    trailInterval: 0.8,
    mass: 12,
    accel: 6.0,
    drag: 0.4,
    leadAccuracy: 0,
    rams: true,
    boost: { multiplier: 2.5, duration: 0.5, cooldown: 2.0, triggerRange: 250 },
    description: '最高速の衝角突撃で敵艦を粉砕する近接特化機。',
    attackDesc: '衝角突撃（高ノックバック）',
  },
  {
    name: 'Launcher',
    size: 11,
    hp: 18,
    speed: 100,
    turnRate: 2,
    fireRate: 2.8,
    range: 420,
    damage: 6,
    shape: 6,
    trailInterval: 0.6,
    mass: 5,
    accel: 5.0,
    drag: 1.5,
    leadAccuracy: 0.2,
    burst: 3,
    homing: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 300 },
    description: '誘導ミサイルで目標を追尾する中距離攻撃機。',
    attackDesc: '追尾ミサイル（3連射）',
  },
  {
    name: 'Disruptor',
    size: 9,
    hp: 14,
    speed: 110,
    turnRate: 3,
    fireRate: 4.5,
    range: 200,
    damage: 2,
    shape: 11,
    trailInterval: 0.5,
    mass: 3,
    accel: 7.0,
    drag: 2.0,
    leadAccuracy: 0,
    emp: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 3.5, triggerRange: 200 },
    description: '電磁パルスを放射し、範囲内の全敵を行動不能にする電子戦機。',
    attackDesc: 'EMPバースト（1.5秒スタン）',
  },
  {
    name: 'Beam Frig.',
    size: 13,
    hp: 30,
    speed: 85,
    turnRate: 1.8,
    fireRate: 0.1,
    range: 300,
    damage: 0.8,
    shape: 5,
    trailInterval: 0.6,
    mass: 6,
    accel: 4.0,
    drag: 1.2,
    leadAccuracy: 0,
    beam: true,
    boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.5, triggerRange: 250 },
    description: '単体に集中照射する焼灼ビーム艦。照射持続で威力が逓増する。',
    attackDesc: '集中ビーム（持続照射で威力逓増）',
  },
  {
    name: 'Teleporter',
    size: 8,
    hp: 9,
    speed: 150,
    turnRate: 4,
    fireRate: 0.6,
    range: 160,
    damage: 5,
    shape: 13,
    trailInterval: 0.4,
    mass: 2,
    accel: 8.0,
    drag: 2.5,
    leadAccuracy: 0.3,
    teleports: true,
    description: '空間跳躍で敵陣に転移し、全方位バーストで奇襲する。',
    attackDesc: '空間跳躍→全方位バースト',
  },
  {
    name: 'Arcer',
    size: 10,
    hp: 16,
    speed: 115,
    turnRate: 3,
    fireRate: 2,
    range: 250,
    damage: 4,
    shape: 15,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    leadAccuracy: 0,
    chain: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.5, triggerRange: 220 },
    description: '放電が最大5体の敵に次々と連鎖する電撃艦。',
    attackDesc: 'チェーンライトニング（最大5連鎖）',
  },
];

const _invSqrtMass: number[] = TYPES.map((t) => 1 / Math.sqrt(t.mass));

export function unitType(id: number): UnitType {
  const t = TYPES[id];
  if (t === undefined) throw new RangeError(`Invalid unit type id: ${id}`);
  return t;
}

export function invSqrtMass(id: number): number {
  const v = _invSqrtMass[id];
  if (v === undefined) throw new RangeError(`Invalid unit type id: ${id}`);
  return v;
}

export function unitTypeIndex(name: string): number {
  const idx = TYPES.findIndex((t) => t.name === name);
  if (idx === -1) throw new RangeError(`Unknown unit type name: ${name}`);
  return idx;
}
