import type { UnitType } from './types.ts';
import { NO_FIRE, resolve } from './unit-type-resolve.ts';

/** Attack role units (10) */

export const drone: UnitType = resolve({
  name: 'Drone',
  role: 'attack',
  cost: 1,
  size: 4,
  hp: 3,
  speed: 220,
  turnRate: 5.5,
  fireRate: 0.25,
  range: 110,
  damage: 1,
  shape: 0,
  trailInterval: 0.3,
  mass: 1,
  accel: 10.0,
  drag: 2.5,
  leadAccuracy: 0.3,
  swarm: true,
  engageMin: 15,
  engageMax: 70,
  boost: { multiplier: 1.8, duration: 0.3, cooldown: 2.5, triggerRange: 120 },
  clusterSize: 8,
  description: '編隊連携に特化した無人機。同型機が密集するほど火力が増大する。',
  attackDesc: 'スウォームパルス（近傍密度連動）',
});

export const fighter: UnitType = resolve({
  name: 'Fighter',
  role: 'attack',
  cost: 3,
  size: 7,
  hp: 10,
  speed: 180,
  turnRate: 4.5,
  fireRate: 0.9,
  range: 170,
  damage: 1.5,
  shape: 1,
  trailInterval: 0.5,
  mass: 2,
  accel: 8.0,
  drag: 2.0,
  leadAccuracy: 0.7,
  engageMin: 50,
  engageMax: 130,
  shots: 2,
  salvo: 2,
  cannonOffsets: [
    [0.8125, 0.71875],
    [0.71875, 0.65625],
  ],
  boost: { multiplier: 2.0, duration: 0.4, cooldown: 3.0, triggerRange: 180 },
  retreatHpRatio: 0.3,
  clusterSize: 5,
  description: '翼端4砲から交互に2連ツインバースト射撃を放つ汎用主力機。前線の中核を担う。',
  attackDesc: '2連ツインバースト射撃',
});

export const bomber: UnitType = resolve({
  name: 'Bomber',
  role: 'attack',
  cost: 5,
  size: 10,
  hp: 24,
  speed: 130,
  turnRate: 2.5,
  fireRate: 2.8,
  range: 220,
  damage: 5,
  shape: 2,
  trailInterval: 0.7,
  mass: 4,
  accel: 5.0,
  drag: 1.5,
  leadAccuracy: 0.4,
  aoe: 42,
  carpet: true,
  engageMin: 110,
  engageMax: 200,
  shots: 4,
  boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
  retreatHpRatio: 0.35,
  clusterSize: 4,
  description: '広域爆圧弾を投下する重爆撃機。密集陣形に絶大な効果を発揮。',
  attackDesc: '絨毯爆撃（範囲爆圧ダメージ）',
});

export const cruiser: UnitType = resolve({
  name: 'Cruiser',
  role: 'attack',
  cost: 8,
  size: 15,
  hp: 50,
  speed: 75,
  turnRate: 1.5,
  fireRate: 1.5,
  range: 350,
  damage: 8,
  shape: 3,
  trailInterval: 0.9,
  mass: 10,
  accel: 3.5,
  drag: 1.2,
  leadAccuracy: 0,
  sweep: true,
  engageMin: 180,
  engageMax: 300,
  boost: { multiplier: 1.4, duration: 0.3, cooldown: 5.0, triggerRange: 250 },
  retreatHpRatio: 0.25,
  clusterSize: 2,
  description: '広角ビームで戦域を薙ぎ払う重巡洋艦。制圧力に優れる。',
  attackDesc: '掃射ビーム（±30°弧状一掃）',
});

export const flagship: UnitType = resolve({
  name: 'Flagship',
  role: 'attack',
  cost: 20,
  size: 30,
  hp: 250,
  speed: 55,
  turnRate: 0.5,
  fireRate: 1.8,
  range: 400,
  damage: 10,
  shape: 4,
  trailInterval: 1.3,
  mass: 30,
  accel: 2.0,
  drag: 0.6,
  leadAccuracy: 0.85,
  broadside: true,
  engageMin: 200,
  engageMax: 350,
  clusterSize: 1,
  description: '重砲斉射で中型艦を圧倒する艦隊旗艦。対小型群には脆弱。',
  attackDesc: '蓄砲→3連主砲＋舷側砲（対中型特化）',
});

export const sniper: UnitType = resolve({
  name: 'Sniper',
  role: 'attack',
  cost: 3,
  size: 9,
  hp: 8,
  speed: 90,
  turnRate: 2,
  fireRate: 2.8,
  range: 600,
  damage: 18,
  shape: 8,
  trailInterval: 0.4,
  mass: 3,
  accel: 4.0,
  drag: 1.5,
  leadAccuracy: 0.95,
  massWeight: 0.15,
  engageMin: 300,
  engageMax: 500,
  cooldownResetOnKill: 0.8,
  retreatHpRatio: 0.4,
  clusterSize: 3,
  description: '超長射程の貫通レールガンで高価値目標を狙撃。撃破ごとに装填が加速。',
  attackDesc: '貫通レールガン（撃破時装填加速）',
});

export const lancer: UnitType = resolve({
  name: 'Lancer',
  role: 'attack',
  cost: 6,
  size: 12,
  hp: 55,
  speed: 260,
  turnRate: 2,
  fireRate: NO_FIRE,
  range: 0,
  damage: 0,
  shape: 9,
  trailInterval: 0.8,
  mass: 12,
  accel: 6.0,
  drag: 0.4,
  leadAccuracy: 0,
  rams: true,
  engageMin: 0,
  engageMax: 0,
  boost: { multiplier: 2.5, duration: 0.5, cooldown: 2.0, triggerRange: 250 },
  clusterSize: 3,
  description: '最高速の衝角突撃で敵艦を粉砕する近接特化機。',
  attackDesc: '衝角突撃（高ノックバック）',
});

export const launcher: UnitType = resolve({
  name: 'Launcher',
  role: 'attack',
  cost: 5,
  size: 11,
  hp: 18,
  speed: 100,
  turnRate: 2,
  fireRate: 2.8,
  range: 420,
  damage: 6,
  shape: 10,
  trailInterval: 0.6,
  mass: 5,
  accel: 5.0,
  drag: 1.5,
  leadAccuracy: 0.2,
  shots: 3,
  homing: true,
  engageMin: 250,
  engageMax: 380,
  boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 300 },
  retreatHpRatio: 0.35,
  clusterSize: 3,
  description: '誘導ミサイルで目標を追尾する中距離攻撃機。',
  attackDesc: '追尾ミサイル（3連射）',
});

export const scorcher: UnitType = resolve({
  name: 'Scorcher',
  role: 'attack',
  cost: 5,
  size: 13,
  hp: 30,
  speed: 85,
  turnRate: 1.8,
  fireRate: 0.1,
  range: 300,
  damage: 0.8,
  shape: 12,
  trailInterval: 0.6,
  mass: 6,
  accel: 4.0,
  drag: 1.2,
  leadAccuracy: 0,
  beam: true,
  engageMin: 140,
  engageMax: 260,
  boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.5, triggerRange: 250 },
  retreatHpRatio: 0.3,
  clusterSize: 3,
  description: '単体に集中照射する焼灼ビーム艦。照射持続で威力が逓増する。',
  attackDesc: '集中ビーム（持続照射で威力逓増）',
});

export const arcer: UnitType = resolve({
  name: 'Arcer',
  role: 'attack',
  cost: 4,
  size: 10,
  hp: 16,
  speed: 115,
  turnRate: 3,
  fireRate: 2,
  range: 250,
  damage: 4,
  shape: 14,
  trailInterval: 0.5,
  mass: 3,
  accel: 6.0,
  drag: 1.8,
  leadAccuracy: 0,
  chain: true,
  engageMin: 110,
  engageMax: 220,
  boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.5, triggerRange: 220 },
  retreatHpRatio: 0.35,
  clusterSize: 3,
  description: '放電が最大5体の敵に次々と連鎖する電撃艦。',
  attackDesc: 'チェーンライトニング（最大5連鎖）',
});
