import type { UnitType } from './types.ts';
import { resolve } from './unit-type-resolve.ts';

/** Support role units (5) */

export const healer: UnitType = resolve({
  name: 'Healer',
  cost: 4,
  size: 11,
  hp: 12,
  speed: 130,
  turnRate: 3.5,
  fireRate: 2,
  range: 160,
  damage: 1,
  shape: 5,
  trailInterval: 0.4,
  mass: 2,
  accel: 7.0,
  drag: 2.0,
  leadAccuracy: 0.3,
  role: 'support',
  heals: true,
  supportFollow: 1,
  engageMin: 80,
  engageMax: 140,
  boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.0, triggerRange: 160 },
  retreatHpRatio: 0.4,
  clusterSize: 3,
  description: '修復ビームで味方艦の損傷を回復する支援艦。',
  attackDesc: '修復ビーム（味方HP回復）',
});

export const reflector: UnitType = resolve({
  name: 'Reflector',
  cost: 5,
  size: 13,
  hp: 30,
  speed: 105,
  turnRate: 2.8,
  fireRate: 0.3,
  range: 130,
  damage: 1,
  shape: 6,
  trailInterval: 0.5,
  mass: 3,
  accel: 6.0,
  drag: 1.8,
  leadAccuracy: 0.15,
  role: 'support',
  reflects: true,
  maxEnergy: 40,
  shieldCooldown: 3,
  supportFollow: 0.4,
  engageMin: 30,
  engageMax: 100,
  boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
  retreatHpRatio: 0.35,
  clusterSize: 2,
  description: '攻撃を反射し、周囲の味方にも反射フィールドを展開する防衛艦。',
  attackDesc: 'シールド反射＋味方反射フィールド',
});

export const bastion: UnitType = resolve({
  name: 'Bastion',
  cost: 6,
  size: 14,
  hp: 55,
  speed: 80,
  turnRate: 2.0,
  fireRate: 1.2,
  range: 200,
  damage: 3,
  shape: 15,
  trailInterval: 0.6,
  mass: 6,
  accel: 4.0,
  drag: 1.8,
  leadAccuracy: 0.4,
  role: 'support',
  shields: true,
  maxEnergy: 25,
  energyRegen: 4,
  supportFollow: 0.4,
  engageMin: 70,
  engageMax: 170,
  boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
  retreatHpRatio: 0.3,
  clusterSize: 2,
  description: 'テザービームで味方のダメージを肩代わりしつつ、自身もエネルギーシールドで被弾を軽減する装甲支援艦。',
  attackDesc: 'ダメージ吸収テザー＋自身シールド＋通常射撃',
});

export const amplifier: UnitType = resolve({
  name: 'Amplifier',
  cost: 4,
  size: 12,
  hp: 22,
  speed: 95,
  turnRate: 2.5,
  fireRate: 1.4,
  range: 180,
  damage: 2,
  shape: 16,
  trailInterval: 0.5,
  mass: 4,
  accel: 5.0,
  drag: 1.8,
  leadAccuracy: 0.35,
  role: 'support',
  amplifies: true,
  supportFollow: 1,
  engageMin: 85,
  engageMax: 145,
  boost: { multiplier: 1.4, duration: 0.3, cooldown: 3.5, triggerRange: 180 },
  retreatHpRatio: 0.35,
  clusterSize: 2,
  description: 'テザービームで味方の射撃性能を底上げする電磁増幅支援艦。',
  attackDesc: '射撃バフテザー＋通常射撃',
});

export const catalyst: UnitType = resolve({
  name: 'Catalyst',
  cost: 4,
  size: 12,
  hp: 20,
  speed: 100,
  turnRate: 2.5,
  fireRate: 1.6,
  range: 160,
  damage: 1,
  shape: 18,
  trailInterval: 0.5,
  mass: 4,
  accel: 5.5,
  drag: 2.0,
  leadAccuracy: 0.25,
  role: 'support',
  catalyzes: true,
  supportFollow: 1,
  engageMin: 90,
  engageMax: 150,
  boost: { multiplier: 1.3, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
  retreatHpRatio: 0.35,
  clusterSize: 2,
  description: '味方艦の機動力と発射速度を底上げするフィールド触媒支援艦。範囲内の味方は加速・旋回・射撃が向上する。',
  attackDesc: '加速フィールド（味方バフ）＋通常射撃',
});
