import type { UnitType } from './types.ts';

/** 射撃を行わないユニット用のダミー fireRate（cooldown が実質満了しない大きな値） */
const NO_FIRE = 999;

/** resolve() が自動補完する UnitType のデフォルト値プロパティ群 */
type DefaultKeys =
  | 'aoe'
  | 'carpet'
  | 'beam'
  | 'heals'
  | 'reflects'
  | 'spawns'
  | 'homing'
  | 'rams'
  | 'emp'
  | 'teleports'
  | 'chain'
  | 'sweep'
  | 'swarm'
  | 'broadside'
  | 'shots'
  | 'salvo'
  | 'massWeight'
  | 'shields'
  | 'amplifies'
  | 'scrambles'
  | 'catalyzes'
  | 'supportFollow'
  | 'maxEnergy'
  | 'energyRegen'
  | 'shieldCooldown';

const DEFAULTS: Pick<UnitType, DefaultKeys> = {
  aoe: 0,
  carpet: false,
  beam: false,
  heals: false,
  reflects: false,
  spawns: false,
  homing: false,
  rams: false,
  emp: false,
  teleports: false,
  chain: false,
  sweep: false,
  swarm: false,
  broadside: false,
  shots: 1,
  salvo: 0,
  massWeight: 0,
  shields: false,
  amplifies: false,
  scrambles: false,
  catalyzes: false,
  supportFollow: false,
  maxEnergy: 0,
  energyRegen: 0,
  shieldCooldown: 0,
};

function resolve(partial: Omit<UnitType, DefaultKeys> & Partial<Pick<UnitType, DefaultKeys>>): UnitType {
  return { ...DEFAULTS, ...partial };
}

export const TYPES: UnitType[] = [
  resolve({
    name: 'Drone',
    size: 4,
    hp: 3,
    speed: 220,
    turnRate: 5.5,
    fireRate: 0.25,
    range: 110,
    damage: 1,
    shape: 0,
    trailInterval: 0.3,
    mass: 1,
    accel: 10.0,
    drag: 2.5,
    leadAccuracy: 0.3,
    swarm: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 2.5, triggerRange: 120 },
    description: '編隊連携に特化した無人機。同型機が密集するほど火力が増大する。',
    attackDesc: 'スウォームパルス（近傍密度連動）',
  }),
  resolve({
    name: 'Fighter',
    size: 7,
    hp: 10,
    speed: 180,
    turnRate: 4.5,
    fireRate: 0.9,
    range: 170,
    damage: 1.5,
    shape: 1,
    trailInterval: 0.5,
    mass: 2,
    accel: 8.0,
    drag: 2.0,
    leadAccuracy: 0.7,
    shots: 2,
    salvo: 2,
    // SDF local coords → unit size比率: Front (0.52,±0.46)/0.64, Rear (0.46,±0.42)/0.64
    cannonOffsets: [
      [0.8125, 0.71875],
      [0.71875, 0.65625],
    ],
    boost: { multiplier: 2.0, duration: 0.4, cooldown: 3.0, triggerRange: 180 },
    retreatHpRatio: 0.3,
    description: '翼端4砲から交互に2連ツインバースト射撃を放つ汎用主力機。前線の中核を担う。',
    attackDesc: '2連ツインバースト射撃',
  }),
  resolve({
    name: 'Bomber',
    size: 10,
    hp: 20,
    speed: 120,
    turnRate: 2.5,
    fireRate: 2.8,
    range: 220,
    damage: 5,
    shape: 2,
    trailInterval: 0.7,
    mass: 4,
    accel: 5.0,
    drag: 1.5,
    leadAccuracy: 0.4,
    aoe: 42,
    carpet: true,
    shots: 4,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
    retreatHpRatio: 0.35,
    description: '広域爆圧弾を投下する重爆撃機。密集陣形に絶大な効果を発揮。',
    attackDesc: '絨毯爆撃（範囲爆圧ダメージ）',
  }),
  resolve({
    name: 'Cruiser',
    size: 15,
    hp: 50,
    speed: 75,
    turnRate: 1.5,
    fireRate: 1.5,
    range: 350,
    damage: 8,
    shape: 16,
    trailInterval: 0.9,
    mass: 10,
    accel: 3.5,
    drag: 1.2,
    leadAccuracy: 0,
    sweep: true,
    boost: { multiplier: 1.4, duration: 0.3, cooldown: 5.0, triggerRange: 250 },
    retreatHpRatio: 0.25,
    description: '広角ビームで戦域を薙ぎ払う重巡洋艦。制圧力に優れる。',
    attackDesc: '掃射ビーム（±30°弧状一掃）',
  }),
  resolve({
    name: 'Flagship',
    size: 30,
    hp: 200,
    speed: 55,
    turnRate: 0.5,
    fireRate: 1.8,
    range: 400,
    damage: 8,
    shape: 24,
    trailInterval: 1.3,
    mass: 30,
    accel: 2.0,
    drag: 0.6,
    leadAccuracy: 0.85,
    broadside: true,
    description: '重砲斉射で中型艦を圧倒する艦隊旗艦。対小型群には脆弱。',
    attackDesc: '蓄砲→3連主砲＋舷側砲（対中型特化）',
  }),
  resolve({
    name: 'Healer',
    size: 11,
    hp: 12,
    speed: 130,
    turnRate: 3.5,
    fireRate: 2,
    range: 160,
    damage: 1,
    shape: 25,
    trailInterval: 0.4,
    mass: 2,
    accel: 7.0,
    drag: 2.0,
    leadAccuracy: 0.3,
    heals: true,
    supportFollow: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.0, triggerRange: 160 },
    retreatHpRatio: 0.4,
    description: '修復ビームで味方艦の損傷を回復する支援艦。',
    attackDesc: '修復ビーム（味方HP回復）',
  }),
  resolve({
    name: 'Reflector',
    size: 13,
    hp: 30,
    speed: 105,
    turnRate: 2.8,
    fireRate: 0.3,
    range: 130,
    damage: 1,
    shape: 26,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    leadAccuracy: 0.15,
    reflects: true,
    maxEnergy: 50,
    shieldCooldown: 3,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
    retreatHpRatio: 0.35,
    description: '攻撃を反射し、周囲の味方にも反射フィールドを展開する防衛艦。',
    attackDesc: 'シールド反射＋味方反射フィールド',
  }),
  resolve({
    name: 'Carrier',
    size: 22,
    hp: 90,
    speed: 50,
    turnRate: 1,
    fireRate: 1.2,
    range: 250,
    damage: 2,
    shape: 7,
    trailInterval: 1,
    mass: 15,
    accel: 2.5,
    drag: 0.9,
    leadAccuracy: 0.5,
    spawns: true,
    retreatHpRatio: 0.3,
    description: 'ドローンを定期射出する母艦。自身も砲撃で援護する。',
    attackDesc: 'ドローン射出＋砲撃援護',
  }),
  resolve({
    name: 'Sniper',
    size: 9,
    hp: 8,
    speed: 90,
    turnRate: 2,
    fireRate: 2.8,
    range: 600,
    damage: 18,
    shape: 8,
    trailInterval: 0.4,
    mass: 3,
    accel: 4.0,
    drag: 1.5,
    leadAccuracy: 0.95,
    massWeight: 0.15,
    engageMin: 300,
    engageMax: 500,
    cooldownResetOnKill: 0.8,
    retreatHpRatio: 0.4,
    description: '超長射程の貫通レールガンで高価値目標を狙撃。撃破ごとに装填が加速。',
    attackDesc: '貫通レールガン（撃破時装填加速）',
  }),
  resolve({
    name: 'Lancer',
    size: 12,
    hp: 65,
    speed: 260,
    turnRate: 2,
    fireRate: NO_FIRE,
    range: 0,
    damage: 0,
    shape: 9,
    trailInterval: 0.8,
    mass: 12,
    accel: 6.0,
    drag: 0.4,
    leadAccuracy: 0,
    rams: true,
    // retreatHpRatio非対応: ram攻撃(range=0)のためcomputeRetreatForceの重み t.range/d が常に0になる
    boost: { multiplier: 2.5, duration: 0.5, cooldown: 2.0, triggerRange: 250 },
    description: '最高速の衝角突撃で敵艦を粉砕する近接特化機。',
    attackDesc: '衝角突撃（高ノックバック）',
  }),
  resolve({
    name: 'Launcher',
    size: 11,
    hp: 18,
    speed: 100,
    turnRate: 2,
    fireRate: 2.8,
    range: 420,
    damage: 6,
    shape: 6,
    trailInterval: 0.6,
    mass: 5,
    accel: 5.0,
    drag: 1.5,
    leadAccuracy: 0.2,
    shots: 3,
    homing: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 4.0, triggerRange: 300 },
    retreatHpRatio: 0.35,
    description: '誘導ミサイルで目標を追尾する中距離攻撃機。',
    attackDesc: '追尾ミサイル（3連射）',
  }),
  resolve({
    name: 'Disruptor',
    size: 9,
    hp: 14,
    speed: 110,
    turnRate: 3,
    fireRate: 4.5,
    range: 200,
    damage: 2,
    shape: 11,
    trailInterval: 0.5,
    mass: 3,
    accel: 7.0,
    drag: 2.0,
    leadAccuracy: 0,
    emp: true,
    boost: { multiplier: 1.8, duration: 0.3, cooldown: 3.5, triggerRange: 200 },
    retreatHpRatio: 0.35,
    description: '電磁パルスを放射し、範囲内の全敵を行動不能にする電子戦機。',
    attackDesc: 'EMPバースト（1.5秒スタン）',
  }),
  resolve({
    name: 'Scorcher',
    size: 13,
    hp: 30,
    speed: 85,
    turnRate: 1.8,
    fireRate: 0.1,
    range: 300,
    damage: 0.8,
    shape: 5,
    trailInterval: 0.6,
    mass: 6,
    accel: 4.0,
    drag: 1.2,
    leadAccuracy: 0,
    beam: true,
    boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.5, triggerRange: 250 },
    retreatHpRatio: 0.3,
    description: '単体に集中照射する焼灼ビーム艦。照射持続で威力が逓増する。',
    attackDesc: '集中ビーム（持続照射で威力逓増）',
  }),
  resolve({
    name: 'Teleporter',
    size: 8,
    hp: 12,
    speed: 150,
    turnRate: 4,
    fireRate: 0.6,
    range: 160,
    damage: 4,
    shape: 13,
    trailInterval: 0.4,
    mass: 2,
    accel: 8.0,
    drag: 2.5,
    leadAccuracy: 0.3,
    teleports: true,
    description: '空間を3連跳躍し、着地衝撃で敵陣形を崩しつつ精密射撃を放つ次元奇襲機。',
    attackDesc: '3連ブリンク→着地衝撃＋精密射撃（計6発）',
  }),
  resolve({
    name: 'Arcer',
    size: 10,
    hp: 16,
    speed: 115,
    turnRate: 3,
    fireRate: 2,
    range: 250,
    damage: 4,
    shape: 15,
    trailInterval: 0.5,
    mass: 3,
    accel: 6.0,
    drag: 1.8,
    leadAccuracy: 0,
    chain: true,
    boost: { multiplier: 1.6, duration: 0.3, cooldown: 3.5, triggerRange: 220 },
    retreatHpRatio: 0.35,
    description: '放電が最大5体の敵に次々と連鎖する電撃艦。',
    attackDesc: 'チェーンライトニング（最大5連鎖）',
  }),
  resolve({
    name: 'Bastion',
    size: 14,
    hp: 55,
    speed: 80,
    turnRate: 2.0,
    fireRate: 1.2,
    range: 200,
    damage: 3,
    shape: 20,
    trailInterval: 0.6,
    mass: 6,
    accel: 4.0,
    drag: 1.8,
    leadAccuracy: 0.4,
    shields: true,
    maxEnergy: 25,
    energyRegen: 4,
    boost: { multiplier: 1.3, duration: 0.3, cooldown: 4.0, triggerRange: 200 },
    retreatHpRatio: 0.3,
    description: 'テザービームで味方のダメージを肩代わりしつつ、自身もエネルギーシールドで被弾を軽減する装甲支援艦。',
    attackDesc: 'ダメージ吸収テザー＋自身シールド＋通常射撃',
  }),
  resolve({
    name: 'Amplifier',
    size: 12,
    hp: 22,
    speed: 95,
    turnRate: 2.5,
    fireRate: 1.4,
    range: 180,
    damage: 2,
    shape: 28,
    trailInterval: 0.5,
    mass: 4,
    accel: 5.0,
    drag: 1.8,
    leadAccuracy: 0.35,
    amplifies: true,
    supportFollow: true,
    boost: { multiplier: 1.4, duration: 0.3, cooldown: 3.5, triggerRange: 180 },
    retreatHpRatio: 0.35,
    description: 'テザービームで味方の射撃性能を底上げする電磁増幅支援艦。',
    attackDesc: '射撃バフテザー＋通常射撃',
  }),
  resolve({
    name: 'Scrambler',
    size: 11,
    hp: 18,
    speed: 105,
    turnRate: 2.8,
    fireRate: NO_FIRE,
    range: 0,
    damage: 0,
    shape: 29,
    trailInterval: 0.5,
    mass: 3,
    accel: 5.5,
    drag: 1.8,
    leadAccuracy: 0,
    scrambles: true,
    supportFollow: true,
    boost: { multiplier: 1.5, duration: 0.3, cooldown: 3.5, triggerRange: 130 },
    retreatHpRatio: 0.4,
    description: '電磁妨害波で敵の射撃性能を劣化させる電子戦支援艦。範囲内の敵は射程・精度・発射速度が低下する。',
    attackDesc: '電磁妨害フィールド（敵デバフ）',
  }),
  resolve({
    name: 'Catalyst',
    size: 12,
    hp: 20,
    speed: 70,
    turnRate: 2.0,
    fireRate: 1.6,
    range: 160,
    damage: 1,
    shape: 30,
    trailInterval: 0.5,
    mass: 4,
    accel: 4.0,
    drag: 2.0,
    leadAccuracy: 0.25,
    catalyzes: true,
    supportFollow: true,
    boost: { multiplier: 1.3, duration: 0.3, cooldown: 3.5, triggerRange: 150 },
    retreatHpRatio: 0.35,
    description: '味方艦の機動力と発射速度を底上げするフィールド触媒支援艦。範囲内の味方は加速・旋回・射撃が向上する。',
    attackDesc: '加速フィールド（味方バフ）＋通常射撃',
  }),
];

const _invSqrtMass: number[] = TYPES.map((t) => 1 / Math.sqrt(t.mass));

export function unitType(id: number): UnitType {
  const t = TYPES[id];
  if (t === undefined) throw new RangeError(`Invalid unit type id: ${id}`);
  return t;
}

export function invSqrtMass(id: number): number {
  const v = _invSqrtMass[id];
  if (v === undefined) throw new RangeError(`Invalid unit type id: ${id}`);
  return v;
}

export function unitTypeIndex(name: string): number {
  const idx = TYPES.findIndex((t) => t.name === name);
  if (idx === -1) throw new RangeError(`Unknown unit type name: ${name}`);
  return idx;
}

/** Flagship エンジンY軸オフセット比率 — 左右対称 × 2段 = 計4基 */
export const FLAGSHIP_ENGINE_OFFSETS = [0.18, 0.38] as const;
